# Generated by Django 4.2.1 on 2023-06-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0004_alter_book_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="source_published",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
