# Generated by Django 4.2.1 on 2023-06-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0004_books_categories_publisher_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="categories",
            field=models.ManyToManyField(blank=True, to="frontend.categories"),
        ),
        migrations.AddField(
            model_name="books",
            name="publisher",
            field=models.ManyToManyField(blank=True, to="frontend.publisher"),
        ),
        migrations.AlterField(
            model_name="books",
            name="cover",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="books",
            name="published",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="books",
            name="source_published",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="books",
            name="url",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
