# Generated by Django 4.2.1 on 2023-06-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "frontend",
            "0005_books_categories_books_publisher_alter_books_cover_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="source_id",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
