# Generated by Django 4.2.1 on 2023-06-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0006_books_source_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="summery",
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
