# Generated by Django 4.2.1 on 2023-06-20 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "frontend",
            "0006_remove_user_maybe_to_read_remove_user_want_to_read_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UserList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maybe_to_read",
                    models.ManyToManyField(
                        blank=True,
                        related_name="maybe_to_read_book",
                        to="frontend.book",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="frontend.user"
                    ),
                ),
                (
                    "want_to_read",
                    models.ManyToManyField(
                        blank=True, related_name="want_to_read_book", to="frontend.book"
                    ),
                ),
                (
                    "wont_read",
                    models.ManyToManyField(
                        blank=True, related_name="wont_read_book", to="frontend.book"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UserBookList",
        ),
    ]
