# Generated by Django 4.2.1 on 2023-06-06 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0007_books_summery"),
    ]

    operations = [
        migrations.RenameField(
            model_name="books",
            old_name="summery",
            new_name="summary",
        ),
    ]
