# Generated by Django 4.2.1 on 2023-06-07 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0010_user_remove_book_source_id_book_source_userbook_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.AlterField(
            model_name="user",
            name="maybe_to_read",
            field=models.ManyToManyField(
                blank=True, related_name="maybe_to_read_book", to="frontend.book"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="want_to_read",
            field=models.ManyToManyField(
                blank=True, related_name="want_to_read_book", to="frontend.book"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="wont_read",
            field=models.ManyToManyField(
                blank=True, related_name="wont_read_book", to="frontend.book"
            ),
        ),
        migrations.AlterField(
            model_name="userbook",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="frontend.user",
                verbose_name="User Added Book",
            ),
        ),
    ]
